version: '3'

services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres-manlib-db"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=manlibdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5434
    ports:
      - "5434:5434"
    command: -p 5434
  manlib:
    depends_on:
      - postgres
    image: manlibapplication
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5434/manlibdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9095:9095"
volumes:
  postgres-data: