apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: deploy
  name: postgres-manlib-db
spec:
  serviceName: postgres-manlib-db
  replicas: 1
  selector:
    matchLabels:
      app: postgres-manlib-db
  template:
    metadata:
      labels:
        app: postgres-manlib-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        volumeMounts:
        - name: postgres-db-disk
          mountPath: /data
        ports:
        - containerPort: 5434
        envFrom:
        - secretRef:
            name: manlib-db-secrets
      volumes:
      - name: postgres-db-disk
        persistentVolumeClaim:
          claimName: postgres-db-disk
  volumeClaimTemplates:
  - metadata:
      name: postgres-db-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Gi
